driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: fedora-25

suites:
- name: default
  run_list: ["recipe[selinux]"]
  attributes: {}
